# Generated by Django 3.2 on 2022-02-15 20:00

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.CharField(choices=[('Draft', 'Draft'), ('hold', 'hold'), ('publish', 'publish')], default='Draft', max_length=40, verbose_name='Post Details')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Post Date')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique_with=['id'])),
                ('description', models.TextField(blank=True, null=True, verbose_name='Blog Description')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image link')),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta Title')),
                ('meta_short_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Short Description')),
                ('meta_tags', models.CharField(blank=True, max_length=50, null=True, verbose_name='Meta Tags')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
    ]
