# Generated by Django 3.2 on 2022-04-11 18:05

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.CharField(choices=[('Draft', 'Draft'), ('hold', 'hold'), ('publish', 'publish')], default='Draft', max_length=40, verbose_name='Post Details')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Post Date')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique_with=['id'])),
                ('description', models.TextField(blank=True, null=True, verbose_name='Blog Description')),
                ('image', models.URLField(blank=True, default='https://res.cloudinary.com/anmoldev/image/upload/v1645629950/Screenshot_from_2022-02-23_20-53-28_aynez4.png', max_length=1000, null=True, verbose_name='Image link')),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Title')),
                ('meta_short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('meta_tags', models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta Tags')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'The Email Field you entered is not unique.'}, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Post Date')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('query', models.CharField(blank=True, max_length=150, null=True, verbose_name='Query')),
                ('message', models.TextField(verbose_name='Message')),
                ('Reference_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Reference link')),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
    ]
