# Generated by Django 3.2 on 2022-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'The Email Field you entered is not unique.'}, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Post Date')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('query', models.CharField(blank=True, max_length=150, null=True, verbose_name='Query')),
                ('message', models.TextField(verbose_name='Message')),
                ('Reference_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Reference link')),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
    ]
