# Generated by Django 3.2 on 2022-04-11 18:05

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fresherjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.CharField(choices=[('Draft', 'Draft'), ('hold', 'hold'), ('publish', 'publish')], default='Draft', max_length=40, verbose_name='Post Details')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Post Date')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique_with=['id'])),
                ('description', models.TextField(blank=True, null=True, verbose_name='Blog Description')),
                ('image', models.URLField(blank=True, default='https://res.cloudinary.com/anmoldev/image/upload/v1645635518/Screenshot_from_2022-02-23_22-25-18_eoq6r9.png', max_length=1000, null=True, verbose_name='Image link')),
                ('application_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Form link')),
                ('company', models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Name')),
                ('job_experience', models.CharField(blank=True, max_length=500, null=True, verbose_name='Job Experience')),
                ('salary', models.CharField(blank=True, max_length=500, null=True, verbose_name='Salary')),
                ('passing_year', models.CharField(blank=True, max_length=500, null=True, verbose_name='Passing Year')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Location')),
                ('degree', models.CharField(blank=True, max_length=500, null=True, verbose_name='Degree')),
                ('role_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Role Name')),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Title')),
                ('meta_short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('meta_tags', models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta Tags')),
            ],
            options={
                'verbose_name': 'Fresherjob',
            },
        ),
        migrations.CreateModel(
            name='jovvacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Post Date')),
                ('company', models.CharField(max_length=500, verbose_name='Company Name')),
                ('location', models.CharField(max_length=500, verbose_name='Location')),
                ('role_name', models.CharField(max_length=500, verbose_name='Role Name')),
                ('job_experience', models.CharField(max_length=500, verbose_name='Job Experience')),
                ('qualifications', models.CharField(max_length=500, verbose_name='Qualifications')),
                ('application_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Reference link')),
            ],
            options={
                'verbose_name': 'Vacancie',
            },
        ),
        migrations.CreateModel(
            name='jobcommments',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500, verbose_name='User Name')),
                ('email', models.EmailField(max_length=500, verbose_name='User Email')),
                ('comments', models.TextField()),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('approvel', models.BooleanField()),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fresherjob.fresherjob')),
            ],
            options={
                'verbose_name': 'Job Comments',
            },
        ),
    ]
