# Generated by Django 3.2 on 2022-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresherjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherjob',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Name'),
        ),
    ]
